### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by oberon2007** [metti/command-not-found#8]
The latest release of command-not-found is now 3 years old! ;)
Are you considering another one or should we just use git-sources?

**Comment by metti** [comment]
I will prepare a release soon. 0.4.5 is in addition broken for gcc6 due to the default c++ standard change. latest master builds fine though.

**Comment by metti** [comment]
fixed with v0.5.0

**Comment by oberon2007** [comment]
Thank you! :-)
